version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fiscal_contratos_db
    restart: always
    environment:
      POSTGRES_USER: fabioadmin
      POSTGRES_PASSWORD: fabiosenha
      POSTGRES_DB: fiscal_contratos
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
      image: dpage/pgadmin4
      container_name: fiscal_contratos_pgadmin
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@fiscal.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      depends_on:
        - postgres

volumes:
  pgdata: